# Generated by Django 2.1.7 on 2019-07-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hobbies',
            field=models.TextField(),
        ),
    ]
