# Generated by Django 2.1.7 on 2019-07-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190723_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dp',
            field=models.ImageField(upload_to='.pics/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='x',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='xii',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
