# Generated by Django 2.1.7 on 2019-07-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190724_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='x',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='xii',
            field=models.CharField(max_length=5),
        ),
    ]
