# Generated by Django 2.1.7 on 2019-07-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190724_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dp',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
