# Generated by Django 2.1.7 on 2019-08-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20190724_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dp',
            field=models.ImageField(upload_to='models/pics'),
        ),
    ]
