# Generated by Django 2.1.7 on 2019-08-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20190803_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dp',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
