# Generated by Django 2.1.7 on 2019-08-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('logo', models.ImageField(upload_to='itemPhoto')),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cate', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=15)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
